steps:
  - label: ":cypress: Cypress"
    command: |
      cypress install
      npx cypress run --key $CYPRESS_KEY && export RESULT="$$?" || export RESULT="$$?"
      if [[ "$RESULT" != "0" ]]; then 
        buildkite-agent artifact upload "cypress/screenshots/**/*" && exit 1
      fi
    agents:
      queue: "nodejs-16"
      dind: false
    timeout_in_minutes: 60
