steps:
  - label: ":cypress: Cypress"
    command: |
      apt-get update -qy && apt-get install libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 libxtst6 xauth xvfb -qy
      npm install cypress --save-dev
      npx cypress run --key $CYPRESS_KEY
    agents:
      queue: "nodejs-16"
      dind: false
    timeout_in_minutes: 60
